import { chromium } from "playwright";
const BASE = "https://rosary-eight.vercel.app";
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 390, height: 844 } })).newPage();
await p.goto(`${BASE}/`, { waitUntil: "networkidle" });
console.log("1) 미로그인 접근 →", new URL(p.url()).pathname, "(/login 기대)");
await p.getByPlaceholder(/이름/).fill("김민수");
await p.getByPlaceholder(/세례명/).fill("브루노");
await p.getByPlaceholder(/PIN/).fill("0214");
await p.getByRole("button", { name: "로그인" }).click();
await p.waitForURL((u) => new URL(u).pathname === "/", { timeout: 12000 }).catch(() => {});
const path = new URL(p.url()).pathname;
console.log("2) 로그인 결과 →", path === "/" ? "🎉 홈 진입: " + (await p.locator("h1").first().innerText()) : "❌ 실패 " + path);
await p.screenshot({ path: "scripts/shots/40-prod.png", fullPage: true });
await b.close();
